### ISSUE TITLE
How to expose variables such as threshold to a gui?

### ISSUE THREAD

**Issue by interior-night** [leozimmerman/ofxFilterbank#1]
I'm using ofxDatGui but could also use ofxGui. I'd like to have sliders control variables such as threshold, as per your vimeo example. Sorry, this is probably very simple but I'm a beginner. Any tips?

**Comment by leozimmerman** [comment]
there's a public var named treshold, try:
`filterBank.treshold = guiSlider;`

**Comment by interior-night** [comment]
Ok. Great. In my case I've got it working with `thresholdSlider->bind(filterBank.treshold);` Would the recommended range of the ofParameter be something like 0.006 to 0.05 with a default value of 0.01?

**Comment by interior-night** [comment]
And could you also recommend the range of sliders bound to pitchDev, maskAmnt, smoothAmnt and EstimateMax? Btw, I'm noticing that moving the EstimateMax slider affects the threshold and vice-versa so is that a constant instead of a variable?
